version: "3.9"

services:
  quote-manager:
    container_name: quote-manager
    image: quote-manager
    # environment:
    #   - JWT_SECRET=jwtsecret
    restart: always
    ports:
      - "3002:3000"
    labels:
      - "traefik.http.routers.quote-manager.rule=Host(`quote.navong.xyz`)"
      # - "traefik.http.services.quote-manager.loadbalancer.server.port=5000"
    networks:
      - traefik-network

networks:
  traefik-network:
    external: true  # Uses the same network as the Traefik and other services
